---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: webapp
  spec:
    template:
      metadata:
        labels:
          run: webapp
      spec:
        containers:
          - name: webapp
            image: riccardomc/k8sbhw-webapp:latest
            ports:
              - containerPort: 9009
- apiVersion: v1
  kind: Service
  metadata:
    name: webapp
    labels:
      run: webapp
  spec:
    type: NodePort
    ports:
    - port: 9009
      nodePort: 32009
    selector:
      run: webapp
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: test-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/rewrite-target: /
  spec:
    backend:
      serviceName: default-http-backend
      servicePort: 80
    rules:
    - http:
        paths:
        - path: /webapp
          backend:
            serviceName: webapp
            servicePort: 9009
        - path: /
          backend:
            serviceName: webapp
            servicePort: 80
