apiVersion: batch/v1
kind: Job
metadata:
  name: database-init
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "sql"
          - "--insecure"
          - "--host=cockroachdb-public"
          - "-e CREATE DATABASE gorm"
      restartPolicy: OnFailure
