---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: webapp
  spec:
    template:
      metadata:
        labels:
          run: webapp
      spec:
        containers:
          - name: webapp
            image: riccardomc/k8sbhw-webapp:latest
            env:
            - name: SQL_DATASTORE_CONNECTION
              value: host=cockroachdb-public port=26257 user=root dbname=gorm sslmode=disable
            ports:
              - containerPort: 9009

- apiVersion: v1
  kind: Service
  metadata:
    name: webapp
    labels:
      run: webapp
  spec:
    ports:
    - port: 9009
      targetPort: 9009
    selector:
      run: webapp


- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: frontend
  spec:
    template:
      metadata:
        labels:
          run: frontend
      spec:
        containers:
          - name: frontend
            image: riccardomc/k8sbhw-frontend:latest
            ports:
              - containerPort: 80

- apiVersion: v1
  kind: Service
  metadata:
    name: frontend
    labels:
      run: frontend
  spec:
    type: NodePort
    ports:
      - port: 80
        nodePort: 32080
    selector:
      run: frontend
