---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: webapp
  spec:
    template:
      metadata:
        labels:
          run: webapp
      spec:
        containers:
          - name: webapp
            image: riccardomc/k8sbhw-webapp:latest
            ports:
              - containerPort: 9009
          - name: frontend
            image: riccardomc/k8sbhw-frontend:latest
            ports:
              - containerPort: 80

- apiVersion: v1
  kind: Service
  metadata:
    name: frontend
    labels:
      run: frontend
  spec:
    type: NodePort
    ports:
      - port: 80
        nodePort: 32080
    selector:
      run: webapp
